---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint
        args: ["-r", "~MD013"]
  - repo: https://github.com/btford/write-good
    rev: v1.0.4
    hooks:
      - id: write-good
  - repo: https://github.com/amperser/proselint
    rev: 0.12.0
    hooks:
      - id: proselint
        name: proselint
        files: "\\.(rst|md|markdown|mdown|mkdn)$"
