baseurl = "https://austinmcconnell.me/"
languageCode = "en-us"
title = "Austin McConnell - Software Developer"
theme = "hugo-strata-theme"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Austin McConnell"
	description = "I am software developer who builds performant web apps, REST APIs, and ETL Pipelines."

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		avatar = "avatar.jpg"
		bio = "Software Developer, <br> Travel Enthusiast, <br> & Coffee Geek"
		#bio = "**I'm Strata**, a super simple<br> responsive site template freebie<br> crafted by [HTML5 UP](//html5up.net)."
		twitter = ""
		github = "austinmcconnell"
		gitlab = ""
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = "austinmcconnell"
		keybase = "austinmcconnell"

		copyright = [
			"&copy; Austin McConnell",
			"Images: [Unsplash](//unsplash.com/)"
		]

	[params.rss]
	hide = true


	[params.about]
		hide  = false
		title = "Hi. I'm Austin McConnell."
		content = "I am software developer who builds performant web apps, REST APIs, and ETL Pipelines. I emphasize clean, maintainable code with a focus on readability and language-specific best practices. I build fully automated CI/CD pipelines and I practice infrastructure-as-code. \n\nI enjoy getting outside to play disc-golf, hike, and explore the outdoors. I'm an avid fantasy reader, and I make a mean cup of coffee."


	[params.portfolio]
		hide  = false
		title = "Portfolio Projects"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = true
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "If you'd like to connect, feel free to reach out using the form below or send me an email directly. Thanks!"

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = ""
		address = [
			"Cedar Park, TX",
			"United States"
		]
		phone = "512-693-9462"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 50 emails each month on their free plan.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "austin@austinmcconnell.dev"
		formspree_form_id="mwkadpgp"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Resume"
	url  = "resume/"
	weight = 20

[[menu.main]]
	name = "Portfolio"
	url  = "portfolio/"
	weight = 30

#[[menu.main]]
#	name = "Blog"
#	url  = "blog/"
#	weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
